travis:
  secure:
    BINSTAR_TOKEN: 4/eYD2BUI2Zv24aR8fLIEudn7kVvQTmwilIyC4tH12F7pFAHadBuKzis9K446BFJJwfn4mJ5SBZnCDQND4csNEe3Qni0Crq96oXGBacZSI7uedRgvKqx75OgJy85DW5YWBZqDy6uppbZI/vkWHNFM/O66lmKp5XZtMvULW+Uvf9KaoE3JHafOC5MHjJRN7tEOQMvzTe6l9ZzzZH/KQdpqtBMg3IfiY8mqXioESZQPvnHPHRwkxupG7m08fp+Se1/1x20tkjYcno07bX0DXpdFDiiekvI1vW0ftkW69yBrg//nHSa2ulkrZuKJ+3DRdnN8slkF5+ti8KT+chOC/LVf4Tguut1cUn0XEjZletcdTMODJrPb68IWF8BuqabwmLDKXdPX1EAqxOBjowftL/HeAKcpZ4Xe59zylxNVqN4Qn0LCeMKvmtnyfoezZ2l8zuqgTuGxQkx03oUm0Vugy/ojdNKaJNNAlsNsNwk7zUxKadPI7svLOKYldjEyZ3DKDM/DA4k8LQEu11smhI76HTAZ5qBqSy1m6WOiU8jsCyjAgt6speiGZ0aS1Lzs3m/wPsMza9orC8n96aLyjfdYf+Mfm1slwzalcdMvm/BUT4sFxXqbWfwNc8N+ghRdq4FWulxgCAaAaX8cT5IlwwtbqbYlRywQuMjml6h3MLOernzCYk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
